### ISSUE TITLE
quill v2 compatiblity

### ISSUE THREAD

**Issue by Ehyiah** [NoelOConnell/quill-image-uploader#99]
Hello,

I will start by a Thanks for this module, using it on quill v1 for some months now.

Do you have any prevision for a compatiblity with QuillJS V2 ? (in RC2 when I write this message), I can not install as the package.json won't allow it, as quill is marked as compatible with ^1.3.7, so the v2 is out of range.

Thanks.

**Comment by saulfrr** [comment]
Hi, same question here. Now that Quill Version 2.0.0-rc.2 is there, do you have plans to support it?

Thanks.

**Comment by CasperNH** [comment]
+1 Hope to see this as well.

**Comment by overcatbe** [comment]
Yes, so this is not compatible with the quill 2 as of yet. 
It manages to upload the images but then we have an error here 
quill.imageUploader.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ops')
    at e.value (quill.imageUploader.min.js:1:6212)
    at e.value (quill.imageUploader.min.js:1:5953)
    at quill.imageUploader.min.js:1:5574

**Comment by kejianfeng** [comment]
+1 Hope to see this as well.
